---
title: "CoReNat_palaeo_summary_plots"
author: "Rachael Holmes"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
classoption: landscape
---


### Load libraries

```{r, warning=FALSE}

options(tidyverse.quiet = TRUE)
library(tidyverse) # for syntax
library(readxl) # read excel files
library(riojaPlot) # for plotting
library(vegan) # for rarefy function
library(broom) # to apply lm to all groups
```

### Set up data

```{r, warning=FALSE}


MHc <- read.csv("MH_ages.csv")
LKNc <- read.csv("LKN_age.csv")
LKREc <- read.csv("LKRE_age.csv")

gp_lookup <- read_csv("Groups.csv")

allpoll_list <- rio::import_list("cores_dates.xlsx")

allpoll_nested <- tibble(Site=names(allpoll_list), polldata=allpoll_list) 

```

## Plotting

```{r}
# function for editing all core data frames in the same way

fun_long_tidy <- function(x) {
  x_long <- x %>% 
    pivot_longer(cols=-c("Depth","Age_BP"),                   
                 names_to="VarName", values_to="Count")%>%
    replace(is.na(.), 0) %>%
    left_join(gp_lookup, by = join_by("VarName"))%>%
    group_by(Depth, Pollen_type2) %>%
    mutate(Total = sum(Count)) %>%
  slice_head() %>%
    ungroup() %>%
    group_by(Depth) %>%
    mutate(hund = sum(Total)) %>%
  filter(hund >= 100) %>% # removes samples with counts under 100
  ungroup()%>%
    group_by(Depth) %>%
  mutate(Percent = Total / sum(Total) * 100) %>% # calculate %
  ungroup() %>%
    arrange(hab_no, Lifeform, Family, Pollen_type2) %>%
   select(-Family, -VarName, -Lifeform,  -habitat, -hab_no, 
          -zone_MH, -zone_no, -Order, -Count, -TNumber, -Group, -zone_LK, -ref)
}

# 

# can use nested or in long format

poll_long <- allpoll_nested %>% 
  mutate(polldata, polldata = map(polldata, ~ fun_long_tidy(.x))) %>%
  unnest(cols = polldata)

head(poll_long)
```


```{r, fig.width=30, fig.height=7, fig.fullwidth=TRUE}

# data transformations

# pollen

MH_wide <- poll_long %>% # wide for rioja
  filter(Site == "MH") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>% # removes taxa not in core
  pivot_wider(id_cols=c(Depth, Age_BP), 
  names_from = Pollen_type2, values_from = Percent, values_fill=0) 

write.csv(MH_wide, file = "MH_wide_perc.csv")

MH_summary <- poll_long %>% # wide for rioja
  filter(Site == "MH") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>%
  group_by(Depth, habitat2) %>%
  summarise(hab_perc = sum(Percent))

MH_mang <- poll_long %>% # wide for rioja
  filter(Site == "MH") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>%
  group_by(Depth, habitat2) %>%
  summarise(hab_perc = sum(Percent))%>%
  filter(habitat2 == "Mangrove")

MH_avg_hab <- MH_summary %>%
  group_by(habitat2)%>%
  summarise(mean = mean(hab_perc), sd = sd(hab_perc), median = median(hab_perc), min = min(hab_perc), max = max(hab_perc))



poll <- MH_wide %>%
  column_to_rownames(var = "Depth") %>%
  select(-Age_BP)

chron <- MH_wide %>%
  select(Depth, Age_BP)

# calculate of max of each column
mx <- sapply(poll, max)
#create a logical vector which is TRUE for taxa with max < 2
sel <- mx < 2
# creates list of names less than 2%
sel_names <- names(sel[sel]) 


# define a custom function to plot symbols 

symb.fun <- function(x, y, i, nm, style) {
   sel <- x > 0
   if (sum(sel) > 0) {
      points(rep(3, sum(sel)), y[sel], cex=0.3, pch=19, xpd=NA)
   }
}

# create a list of functions of length equal to the number of columns in the data

funlist <- lapply(1:ncol(poll), function(x) symb.fun)

# now set the elements of the list where we don't want to plot symbols to NULL

funlist[!sel] <- list(NULL)

# set up groups

habitat <- gp_lookup %>%
  select(Pollen_type2, habitat2) %>%
  rename(VarName = Pollen_type2) %>%
  group_by(VarName) %>%
  slice_head()%>%
  filter(VarName != "Remove")

habitat$habitat2 <- factor(habitat$habitat2,
                  levels=c("Mangrove","Mixed","Open/disturbance","Non-mangrove arb.", "Ferns", "Unknown"))

earth <- c("darkgreen", "#003f5c","#2aa5a5", "#882d17", "tan", "#CBC3BA")

ytks1 <- seq(0, 600, by = 50) # set up y axis intervals

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Depth",
          scale.percent=TRUE, 
          plot.poly=FALSE,
   plot.bar = !sel,
   lwd.bar=2,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group= earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="auto",
          col.zones="#232023",
          ymin=0, ymax=600,
          ytks1=ytks1,
          srt.xlabel=45
          )

```

MH all by age

```{r, fig.width=30, fig.height=7, fig.fullwidth=TRUE}

depth_beg <- seq(100, 600, by = 50) # set up y axis intervals

beg <- seq(0, 100, by = 10)

ytks1b <- c(beg,depth_beg)

t <- c(-69, -50, 0, 200, 400, 600, 800, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500, 7000, 7500, 8000)

riojaPlot(poll, chron, groups = habitat,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="auto",
          col.zones="#232023",
          ymin=-69, ymax=8000,
          ytks1=t,
          ytks2=ytks1b,
          srt.xlabel=45
          )

## dieback to modern

t3 <- seq(0, 600, by=10)

ytks2 <- seq(-70, 8000, by=5)

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          scale.percent=TRUE, 
          plot.exag= TRUE,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="auto",
          col.zones="#232023",
          ymin=-69, ymax=1500,
          ytks1=ytks2,
          ytks2=t3,
          srt.xlabel=45,
          cex.xlabel=0.7)

#historic diebacks

ytks3 <- seq(-70, 8000, by=5)

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          scale.percent=TRUE, 
          plot.exag= TRUE,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="auto",
          col.zones="#232023",
          ymin=-69, ymax=0,
          ytks1=ytks3,
          ytks2=t3,
          srt.xlabel=45,
          cex.xlabel=0.7)

```


```{r}

t2 <- c(-69, -50, 0, 200, 400, 600, 800, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500, 7000, 7500, 8000)

#Depth and age flipped

riojaPlot(poll, chron, groups = habitat,
          yvar.name="Depth",
          sec.yvar.name="Age_BP",
          plot.sec.axis=TRUE,
          scale.percent=TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="auto",
          col.zones="#232023",
          ymin=0, ymax=600,
          ytks1=ytks1,
          ytks2=t,
          srt.xlabel=45
          )


```


## Diatoms

```{r}

diatoms <- read_excel("Diat.xlsx")

diat_group <- read_excel("Diat_grp.xlsx")

diat_age <- diatoms %>%
  left_join(MHc) %>% # combines dates
  select(c(-min, -max, -median))%>%
  relocate(Age_BP, .after = Depth) %>%
  replace(is.na(.), 0) %>%
  mutate(Age_BP = replace(Age_BP, Age_BP == 0, -69))

# write.csv(diat_age , file = "MH_diat_dates.csv")

diat_age <- read_excel("Diat.xlsx")%>%
  mutate_all(~replace_na(.,0))

```

Set up diatom perc

```{r}

MH_long_d <- diat_age %>% 
  pivot_longer(cols=-c("Depth", "Age_BP"),                   
               names_to="VarName", values_to="Count")

MH_long_d <- MH_long_d %>% 
  group_by(Depth) %>%
  mutate(Percent = Count / sum(Count) * 100) %>%
  ungroup() 

MH_wide_d <- MH_long_d %>% 
  pivot_wider(id_cols=c(Depth, Age_BP), 
  names_from=VarName, values_from=Percent, values_fill=0)

```

Diatom plots 

```{r}

diat <- MH_wide_d %>%
  column_to_rownames(var = "Depth") %>%
  select(-Age_BP)

chron <- MH_wide_d %>%
  select(Depth, Age_BP)

# select variables with maximum value < 5%

# calculate of max of each column
mx <- sapply(diat, max)
#create a logical vector which is TRUE for taxa with max < 2
sel <- mx < 2
# creates list of names less than 2%
sel_names <- names(sel[sel]) 

# define a custom function to plot symbols 

symb.fun <- function(x, y, i, nm, style) {
   sel <- x > 0
   if (sum(sel) > 0) {
      points(rep(3, sum(sel)), y[sel], cex=0.3, pch=19, xpd=NA)
   }
}

# create a list of functions of length equal to the number of columns in the data

funlist <- lapply(1:ncol(diat), function(x) symb.fun)

# now set the elements of the list where we don't want to plot symbols to NULL

funlist[!sel] <- list(NULL)

# set up groups

salinity <- diat_group %>%
  select(Type, Group) %>%
  rename(VarName = Type)

salinity$Group <- factor(salinity$Group,
                      levels=c("Marine", "Marine/Brackish","Brackish/Freshwater", "Freshwater","Mixed" , "Unknown"))

diat_col <- c("#3d5a80", "#98c1d9", "#90e0ef" ,"#ef5675", "#683383", "#CBC3BA")

riojaPlot(diat, chron, groups=salinity,
          yvar.name="Depth",
          scale.percent=TRUE, 
          sep.bar=TRUE,
          lwd.bar = 2,
          plot.poly=FALSE,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=FALSE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group= diat_col,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones= 4,
          col.zones="#232023",
          ymin=0, ymax=600,
          ytks1=ytks1,
          srt.xlabel=45,
   plot.top.axis = TRUE, 
   plot.bottom.axis = FALSE)

#wa.order="bottomleft" # order based on appearance in the record

t <- c(-69, -50, 0, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000)

t2 <- c(0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600)

#ytks2 <- seq(-70, 8800, by=1000)

t3 <- seq(0, 60, by=10)

riojaPlot(diat, chron, groups=salinity,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=TRUE, 
          lwd.bar = 1,
          plot.poly=FALSE,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=FALSE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group= diat_col,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones= 3,
          col.zones="#232023",
          ymin=-69, ymax=8000,
          ytks1=t,
          ytks2=t2,
          srt.xlabel=45)

# close up

riojaPlot(diat, chron, groups=salinity,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=TRUE, 
          plot.poly=FALSE,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=FALSE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          lwd.bar = 1,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group= diat_col,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones= 4,
          col.zones="#232023",
          ymin=-69, ymax=1500,
          ytks1=t,
          ytks2=t3,
          srt.xlabel=45)


```

Non percentage plots

Followed code for rarefaction from Jari Oksanen

```{r}
fun_rare <- function(x) {
   x %>% 
    pivot_longer(cols=-c("Depth","Age_BP"), names_to="VarName", values_to="Count")%>%
    replace(is.na(.), 0) %>%
    group_by(Depth) %>%
    mutate(Total = sum(Count)) %>%
  filter(Total > 100) %>% # removes samples with counts under 100
  ungroup()%>%
    pivot_wider(id_cols=c(Depth, Age_BP), 
  names_from = VarName, values_from = Count, values_fill=0) %>%
   summarise(Depth, Age_BP, richness=rarefy(round(.[, -(1:2)]), 100))
}

# apply fun_rare to our nested list using mutate / map

set.seed(15)

rich <- allpoll_nested %>% 
  mutate(polldata, rare=map(polldata, ~fun_rare(.x))) %>%
  unnest(rare) %>%
  select(-polldata)

MH_rich <- rich %>%
  filter(Site == "MH") %>%
  select(-Site)
  
LKN_rich <- rich %>%
  filter(Site == "LKN") %>%
  select(-Site)

LKRE_rich <- rich %>%
  filter(Site == "LKRE") %>%
  select(-Site)

# apply fun_rare to a subset of the last 1500 years
rich_1500 <- allpoll_nested %>% 
  mutate(polldata = map(polldata, ~ filter(., Age_BP <= 1500)))%>%
  mutate(polldata, rare=map(polldata, ~fun_rare(.x))) %>%
  unnest(rare) %>%
  select(-polldata)

rare_all <- ggplot(rich, aes(Age_BP, richness, col=Site)) +
  geom_line() +
  scale_x_continuous(breaks=seq(0, 20000, by=2000)) +
  scale_colour_brewer(palette = "Set2") +
  theme_bw() +
  theme(legend.position="right", 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  xlab("cal. Age BP") + 
  ylab("Pollen richness")


rare_all_1500 <- ggplot(rich_1500, aes(Age_BP, richness, col=Site)) +
  geom_line() +
  scale_x_continuous(breaks=seq(0, 1500, by=100)) +
  scale_colour_brewer(palette = "Set2") +
  theme_bw() +
  theme(legend.position="right", 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  xlab("cal. Age BP") + 
  ylab("Pollen richness")

rich

# whcih are signifcant

rich3 <- rich %>%
  mutate(neg_Age=-Age_BP) 

# Add a regression line to identify trends
ggplot(rich3, aes(neg_Age, richness, col=Site)) +
  geom_line() +
  geom_smooth(method="lm", se=FALSE) +
  scale_x_continuous(breaks=seq(-9000, 70, by=500)) +
  labs(x="Neg. Years BP") +
  theme(legend.position="none")

if (0) {
rich3 %>%
  group_by(Site) %>%
  summarise(lm(richness ~ neg_Age), .groups="drop") 
}

RoC <- rich3 %>%
  group_by(Site) %>%
  summarise(broom::tidy(lm(richness ~ neg_Age)), .groups="drop") 

RoC

RoC <- rich3 %>%
  group_by(Site) %>%
  summarise(broom::tidy(lm(richness ~ neg_Age)), .groups="drop") %>% 
  filter(term=="neg_Age")

RoC

```


```{r}
# non perc proxies

MH2 <- read.csv("MH_data_2.csv") # second dataset (microcharcoal, concs etc.)
MH_accum <- read.csv("MH_avg_sed_acc.csv")

dat2 <- MH2 %>%
  left_join(MH_accum) %>%
  left_join(MH_rich) %>%
  mutate(influx = Pollen_conc/Mean_sed)%>%
  select(-Pollen_conc, -Mean_sed)%>%
  column_to_rownames(var = "Depth") %>%
  relocate(influx)%>%
  relocate(richness, .after = influx) %>%
  select(-Age_BP, -X)

rich_MH <- MH2 %>%
  left_join(MH_accum) %>%
  left_join(MH_rich) %>%
  mutate(influx = Pollen_conc/Mean_sed)%>%
  select(-Pollen_conc, -Mean_sed)

chron <- MH2 %>%
  select(Depth, Age_BP)

# by depth

riojaPlot(dat2, chron,
          yvar.name="Depth",
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=0, ymax=600,
          ytks1=ytks1,
          srt.xlabel=45
          )

# by age

riojaPlot(dat2, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=8000,
          ytks1=t,
          ytks2=ytks1,
          srt.xlabel=45)

## plotting microcharcoal seperately as bars

microch <- MH2 %>%
  select(Depth, Microcharcoal)%>%
  column_to_rownames(var = "Depth")

riojaPlot(microch, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = TRUE,
   col.bar = "black",
   plot.line=FALSE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=8000,
          ytks1=t,
          ytks2=ytks1,
          srt.xlabel=45)

# plotting richness seperately

richness <- rich_MH %>%
  select(Depth, richness)%>%
  column_to_rownames(var = "Depth")

riojaPlot(richness, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   col.bar = "black",
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=8000,
          ytks1=t,
          ytks2=ytks1,
          srt.xlabel=45)

## LOI

LOI_wide <- read.csv("MH_LOI.csv") %>%
  mutate(Depth = round(Depth)) %>%
  left_join(MHc)%>%
  select(Depth, Age_BP, LOI)

LOI <- LOI_wide %>%
  column_to_rownames(var = "Depth") %>%
  select(-Age_BP)

chron <- LOI_wide %>%
  select(Depth, Age_BP)

riojaPlot(LOI, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
          plot.bar = FALSE,
          plot.line=TRUE,
          plot.symb=TRUE,
          symb.cex=0.4,
          plot.exag=FALSE,
          cex.xlabel=0.7,
          ymin=-69, ymax=8000,
          ytks1=t,
          ytks2=ytks1b,
          srt.xlabel=45)

```

LKN

```{r, fig.width=30, fig.height=7, fig.fullwidth=TRUE}

# transformations

LKN_wide <- poll_long %>% # wide for rioja
  filter(Site == "LKN") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>% # removes taxa not in core
  pivot_wider(id_cols=c(Depth, Age_BP), 
  names_from = Pollen_type2, values_from = Percent, values_fill=0) 

LKN_summary <- poll_long %>% # wide for rioja
  filter(Site == "LKN") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>%
  group_by(Depth, habitat2) %>%
  summarise(hab_perc = sum(Percent))

LKN_mang <- poll_long %>% # wide for rioja
  filter(Site == "LKN") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>%
  group_by(Depth, habitat2) %>%
  summarise(hab_perc = sum(Percent))%>%
  filter(habitat2 == "Mangrove")

LKN_avg_hab <- LKN_summary %>%
  group_by(habitat2)%>%
  summarise(mean = mean(hab_perc), sd = sd(hab_perc), median = median(hab_perc), min = min(hab_perc), max = max(hab_perc))

#write.csv(LKN_wide, file = "LKN_wide.csv")


poll <- LKN_wide %>%
  column_to_rownames(var = "Depth") %>%
  select(-Age_BP)

chron <- LKN_wide %>%
  select(Depth, Age_BP)

# select variables with maximum value > 2%
max2 <- sapply(poll, max) > 2
max2_names <- names(max2[max2]) 

# select variables with maximum value < 5%

# calculate max of each column
mx <- sapply(poll, max)
#create a logical vector which is TRUE for taxa with max < 5
sel <- mx < 2
# creates list of names less than 2%
sel_names <- names(sel[sel]) 

# create a list of functions of length equal to the number of columns in the data

funlist <- lapply(1:ncol(poll), function(x) symb.fun)

# now set the elements of the list where we don't want to plot symbols to NULL

funlist[!sel] <- list(NULL)

ytks1 <- seq(0, 200, by=20)

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Depth",
          scale.percent=TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="2",
          ymin=0, ymax=192,
          ytks1=ytks1,
          srt.xlabel=45)

# age

ytks2 <- c(-69, -50, -30, 0, 50, 100, 150, 170, 200)

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=TRUE, 
         plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones=3,
          col.zones="#232023",
          ymin=-69, ymax=175,
          ytks1=ytks2,
          ytks2=ytks1,
          srt.xlabel=45)
```

```{r}

# Depth and age

ytks1 <- seq(0, 300, by=10) # same length as LKRE

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Depth",
          sec.yvar.name="Age_BP",
          plot.sec.axis=TRUE,
          scale.percent=TRUE, 
         plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="3",
          col.zones="#232023",
          ymin=0, ymax=300,
          ytks1=ytks1,
          ytks2=ytks2,
          srt.xlabel=45)
```

Non perc LKN

```{r}
# non perc proxies

LKN2 <- read.csv("LKN_data_2.csv") # second dataset (microcharcoal, concs etc.)
LKN_accum <- read.csv("LKN_avg_sed_acc.csv")

dat2 <- LKN2 %>%
  left_join(LKN_accum) %>%
  left_join(LKN_rich) %>%
  mutate(influx = Pollen_conc/Mean_sed)%>%
  select(-X, -Pollen_conc, -Mean_sed)%>%
    column_to_rownames(var = "Depth") %>%
  relocate(influx)%>%
  relocate(richness, .after = influx) %>%
  select(-Age_BP)


chron <- LKN2 %>%
  select(Depth, Age_BP)

# by depth

riojaPlot(dat2, chron,
          yvar.name="Depth",
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=0, ymax=300,
          ytks1=ytks1,
          srt.xlabel=45
          )

# by age

riojaPlot(dat2, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=850,
          ytks1=ytks2,
          ytks2=ytks1,
          srt.xlabel=45)
## plotting microcharcoal seperately as bars

microch <- LKN2 %>%
  select(Depth, Microcharcoal)%>%
  column_to_rownames(var = "Depth")

riojaPlot(microch, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = TRUE,
   plot.line=FALSE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=850,
          ytks1=ytks2,
          ytks2=ytks1,
          srt.xlabel=45)


```

LKRE

```{r, fig.width=30, fig.height=7, fig.fullwidth=TRUE}


LKRE_wide <- poll_long %>% # wide for rioja
  filter(Site == "LKRE") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>% # removes taxa not in core
  pivot_wider(id_cols=c(Depth, Age_BP), 
  names_from = Pollen_type2, values_from = Percent, values_fill=0) 

LKRE_summary <- poll_long %>% # wide for rioja
  filter(Site == "LKRE") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>%
  group_by(Depth, habitat2) %>%
  summarise(hab_perc = sum(Percent))

LKRE_mang <- poll_long %>% # wide for rioja
  filter(Site == "LKRE") %>%
  group_by(Pollen_type2) %>%
  mutate(max = max(Percent)) %>%
  ungroup() %>%
  filter(max > 0) %>%
  group_by(Depth, habitat2) %>%
  summarise(hab_perc = sum(Percent))%>%
  filter(habitat2 == "Mangrove")

LKRE_avg_hab <- LKRE_summary %>%
  filter(Depth != 0)%>%
  group_by(habitat2)%>%
  summarise(mean = mean(hab_perc), sd = sd(hab_perc), median = median(hab_perc), min = min(hab_perc), max = max(hab_perc))


#write.csv(LKRE_wide, file = "LKRE_wide.csv")
 

poll <- LKRE_wide %>%
  column_to_rownames(var = "Depth") %>%
  select(-Age_BP)

chron <- LKRE_wide %>%
  select(Depth, Age_BP)

# select variables with maximum value < 5%

# calculate max of each column
mx <- sapply(poll, max)
#create a logical vector which is TRUE for taxa with max < 5
sel <- mx < 2
# creates list of names less than 2%
sel_names <- names(sel[sel]) 

# create a list of functions of length equal to the number of columns in the data

funlist <- lapply(1:ncol(poll), function(x) symb.fun)

# now set the elements of the list where we don't want to plot symbols to NULL

funlist[!sel] <- list(NULL)

ytks1 <- seq(0, 300, by=10)

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Depth",
          scale.percent=TRUE, 
          plot.exag= TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          col.zones="#232023",
          ymin=0, ymax=295,
          ytks1=ytks1,
          srt.xlabel=45)


ytks2 <- c(-69, 70, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850)

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=TRUE, 
          plot.exag= TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones=2,
          col.zones="#232023",
   ymin=-69, ymax=850,
          ytks1=ytks2,
          ytks2=ytks1,
          srt.xlabel=45)

```


```{r}

# Depth and age

riojaPlot(poll, chron, groups=habitat,
          yvar.name="Depth",
          sec.yvar.name="Age_BP",
          plot.sec.axis=TRUE,
          scale.percent=TRUE, 
          plot.exag= TRUE,
          plot.poly=!sel,
   plot.bar = !sel,
   plot.line=FALSE,
   plot.exag=TRUE,
   cex.xlabel=0.7,
   fun.xfront=funlist,
          plot.groups=TRUE,
          plot.cumul=TRUE,
          col.group=earth,
          clust.data.trans="sqrt",
          do.clust=TRUE,
          plot.clust=TRUE,
          plot.zones="3",
          col.zones="#232023",
   ymin=0, ymax=300,
          ytks1=ytks1,
          ytks2=ytks2,
          srt.xlabel=45)




```


Non perc LKRE

```{r}
# non perc proxies

LKRE2 <- read.csv("LKRE_data_2.csv") # second dataset (microcharcoal, concs etc.)
LKRE_accum <- read.csv("LKRE_avg_sed_acc.csv")

dat2 <- LKRE2 %>%
  left_join(LKRE_accum) %>%
  left_join(LKRE_rich) %>%
  mutate(influx = Pollen_conc/Mean_sed)%>%
  select(-Pollen_conc, -Mean_sed)%>%
    column_to_rownames(var = "Depth") %>%
  relocate(influx)%>%
  relocate(richness, .after = influx) %>%
  select(-Age_BP)

chron <- LKRE2 %>%
  select(Depth, Age_BP)

# by depth

riojaPlot(dat2, chron,
          yvar.name="Depth",
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=0, ymax=600,
          ytks1=ytks1,
          srt.xlabel=45
          )

# by age

riojaPlot(dat2, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = FALSE,
   plot.line=TRUE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=670,
          ytks1=ytks2,
          ytks2=ytks1,
          srt.xlabel=45)


## plotting microcharcoal seperately as bars

microch <- LKRE2 %>%
  select(Depth, Microcharcoal)%>%
  column_to_rownames(var = "Depth")

riojaPlot(microch, chron,
          yvar.name="Age_BP",
          sec.yvar.name="Depth",
          plot.sec.axis=TRUE,
          scale.percent=FALSE, 
          plot.poly=FALSE,
   plot.bar = TRUE,
   plot.line=FALSE,
   plot.symb=TRUE,
          symb.cex=0.4,
   plot.exag=FALSE,
   cex.xlabel=0.7,
          ymin=-69, ymax=850,
          ytks1=ytks2,
          ytks2=ytks1,
          srt.xlabel=45)
```


